[project]
name = "understanding_the_universe"
version = "0.1.0"
description = "Add a short description here"
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]
build = """
cd paper && \
myst start
"""

export = """
cd paper && \
myst build --html
"""

export-pdf = """
cd paper && \
myst build --pdf
"""

[dependencies]
mystmd = "==1.3.4"
nodejs = "==20.12.2"
libwebp = "==1.4.0"

[feature.dev.dependencies]
pre-commit = "==3.8.0"

[feature.dev.tasks]
pre-commit = "pre-commit run --all-files"

[environments]
dev = ["dev"]
